### PR TITLE
move to github actions

### PR DESCRIPTION
**Pull request by jneu**
This pull request removes the Travis CI configuration and moves the functionality to Github Actions.

Python 3.6 is no longer supported, and this code will not work on astropy>=5.0 which requires Python 3.8. so it tries to find a middle path by using Python 3.7 and pinning astropy to be strictly less than 5 as a temporary solution.

### CODE REVIEW

**Comment by sean-lockwood** [comment]
Thanks @jneu !
Is the issue with upgrading to 3.8 just the `astroconda` installation dependency?  I should be able to vet the package itself with 3.8 pretty easily.

**Comment by jneu** [comment]
> Thanks @jneu ! Is the issue with upgrading to 3.8 just the `astroconda` installation dependency? I should be able to vet the package itself with 3.8 pretty easily.

I believe the problem is this: stistools requires python <3.8, but astroconda 5.0 requires >=3.8. I'd rather see everything bumped to lastest (astroconda>=5.0, python>=3.8), but I don't know how much work it would be to get stistools upgraded.

**Comment by sean-lockwood** [comment]
Some preliminary manual testing with python=3.8...

Looks like the `stistools` python=3.6 requirement might just be for testing, as it's not in the setup.py file:  
https://github.com/spacetelescope/stistools/blob/master/setup.py#L46  
https://github.com/spacetelescope/stistools/blob/master/Jenkinsfile#L11  

To manually test, I conda-installed `hstcal` and did a local install of `stistools` into a python=3.8 environment.  I pip-installed other dependencies and regenerated STIS reference files for anneal index 251 (2021 DOY231).

```bash
./run_refstis.py run -k -d data/ -o ref_251/ 251
```

Except for trivial header differences related to creation time and CRDS delivery, the weekbiases remain unchanged:
```bash
fitsdiff --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o16375o_bia.fits weekbias_21231_01_gn1.fits
fitsdiff --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o1636ro_bia.fits weekbias_21231_01_gn4.fits
fitsdiff --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o1636to_bia.fits weekbias_21231_02_gn1.fits
fitsdiff --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o16377o_bia.fits weekbias_21231_03_gn1.fits
fitsdiff --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o1637ao_bia.fits weekbias_21231_03_gn4.fits
fitsdiff --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o16378o_bia.fits weekbias_21231_04_gn1.fits
fitsdiff --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o1637co_bia.fits weekbias_21231_05_gn1.fits
fitsdiff --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o1637do_bia.fits weekbias_21231_05_gn4.fits
```

However, the weekdark ext=1 data changed from float64 in the CRDS version to float32 in the local version, but otherwise the files remain unchanged:
```bash
fitsdiff --rtol 1e-7 --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o1636oo_drk.fits weekdark_21231_01.fits
fitsdiff --rtol 1e-7 --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o1636qo_drk.fits weekdark_21231_02.fits
fitsdiff --rtol 1e-7 --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o16374o_drk.fits weekdark_21231_03.fits
fitsdiff --rtol 1e-7 --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o16370o_drk.fits weekdark_21231_04.fits
fitsdiff --rtol 1e-7 --ignore-keywords 'HISTORY,FILENAME' /grp/hst/cdbs/oref/59o16372o_drk.fits weekdark_21231_05.fits
```
This likely shouldn't have been float64 before, and changes are of the order of numerical precision for the change.

This testing doesn't prove `stistools` is ready for general python=3.8 support, but it does show that the parts used by `refstis` for the `basebias`, `basedark`, `refbias`, & `weekdark` algorithms work.

**Comment by sean-lockwood** [comment]
Additionally, I have been running `refstis` locally in python=3.7 and astropy=4.0 successfully.  I think the new build matrix makes sense.

**Pull request merged**
